### ISSUE TITLE
Feature Request: Custom parameter name for SAML tickets

### ISSUE THREAD

**Issue by wflk** [CompassSecurity/SAMLRaider#18]
Would be useful to have ability to set customer parameter name to look for SAML ticket instead of defaults SAMLResponse/SAMLRequest.

**Comment by jemjensen** [comment]
Bump

**Comment by mindfuckup** [comment]
Implemented in https://github.com/CompassSecurity/SAMLRaider/pull/49. Will be available when new version is released.

**Comment by mindfuckup** [comment]
Released https://github.com/CompassSecurity/SAMLRaider/releases/tag/v1.3.0.
