### ISSUE TITLE
Freezing burp suite

### ISSUE THREAD

**Issue by irsdl** [CompassSecurity/SAMLRaider#21]
When the `SAMLResponse` parameter for example is invalid (e.g. SAMLResponse=x), clicking on the SAML Raider tab freezes Burp and I need to close it and re-open it.

**Comment by mindfuckup** [comment]
I did not encouter such an error so far. However, thanks for the bug report! I'll have a look at it when I next code on SAML Raider.

**Comment by mindfuckup** [comment]
I can confirm. :)

**Comment by t-hg** [comment]
Hmm... I cannot reproduce this issue. Will close this for now. If it still happens, please send me the full request.
