### ISSUE TITLE
Not friendly for XXE attacks

### ISSUE THREAD

**Issue by irsdl** [CompassSecurity/SAMLRaider#22]
It seems the extension tries to find the DTD items in the request but it cannot parse it. As a result, when building an XXE attack, it complains and sometimes removes the XXE payload completely.

I think it should try not to parse the DTDs or when DTD is there, it can show an error that it is not going to parse it at all and convert it back to base64 as is.

**Comment by mindfuckup** [comment]
Hi

I noticed that as well during testing and a "RAW Mode" is already planned for a future version. This mode could be activated in order that no further XML parsing is performed when the modified payload is forwarded to the target.

I'll close this issue as soon the RAW mode is implemented. However, I cannot tell when this will happen. I hope soon.

**Comment by mindfuckup** [comment]
This is possible now since the latest release using the raw mode: https://github.com/CompassSecurity/SAMLRaider/releases/tag/v1.4.0
