### ISSUE TITLE
More Features

### ISSUE THREAD

**Issue by mindfuckup** [CompassSecurity/SAMLRaider#28]
* Support for XXE testing
* "RAW" Mode (only Base64 encoding and decoding)
* Support for testing AuthRequests --> Testing the IdP
* create stand alone certificate cloner. --> keystore creator

**Comment by tyanderson** [comment]
- ability to save imported keys as project/user options

**Comment by mindfuckup** [comment]
Done now:
- Support for XXE Testing
- RAW mode
- Support AuthRequests should already work.

**Comment by mindfuckup** [comment]
> * ability to save imported keys as project/user options

That is not possible by design of the Burp API.

**Comment by mindfuckup** [comment]
> * create stand alone certificate cloner. --> keystore creator

This is no SAML Raider related issue,
