### ISSUE TITLE
Re-Sign Message Doesn't Re-Sign Message.. just says "Signing..."

### ISSUE THREAD

**Issue by edmacke** [CompassSecurity/SAMLRaider#42]
I intercepted a SAML response and sent the certificate to the SAML Raider Certs, where I "Save and Self-Sign"-ed the cert.

Back on the SAML Raider tab, the self-signed cert was pre-selected. I clicked "(Re-)Sign Message", and get the message "Signing..." but it _never actually re-signs the message_. It's like the extension displays the message, but doesn't actually do anything.

BurpSuite isn't "hung" or anything; I can forward the request, but the request is not re-signed.

![image](https://user-images.githubusercontent.com/26488296/77657768-bd70ce00-6f43-11ea-91fb-872eb7814b44.png)

**Comment by edmacke** [comment]
Additional clues... the Re-Sign Message function appears to work if there **is not** already a message signature. It appears to fail when there **is** already a message signature.

**Comment by mindfuckup** [comment]
Hi

Which JRE do you use? Do you use the bundled JDK from the Burp Installer? If no, can you try to use this one?

If it does still not work, it it possible that you share your assertion? You can also anonymize it a bit if there is sensitive information in it.

**Comment by edmacke** [comment]
I'm just using the out-of-the-box BurpSuitePro.exe installation, v. 2020.2.1, so I'm assuming it's using the bundled JRE. FYI, SAML Raider is saml-raider-1.2.3-jar-with-dependencies.jar.

I will PM you the SAML response.

**Comment by mindfuckup** [comment]
Thanks. I may have a look into it this week. I'll keep you informed.

**Comment by mindfuckup** [comment]
I just checked your issue.

Digest value from the assertion you sent me:
![image](https://user-images.githubusercontent.com/438188/86252262-46d31480-bbb3-11ea-9ac4-2de81a87c07a.png)

I can sign the assertion with the cloned certificate:
![image](https://user-images.githubusercontent.com/438188/86252382-6ff3a500-bbb3-11ea-9b7f-a6dcb1c4eff1.png)


I can also sign the message with the cloned certificate:
![image](https://user-images.githubusercontent.com/438188/86253343-b695cf00-bbb4-11ea-985e-64b0f622b449.png)


So, I could not reproduce the issue.

I use the up-to-date Burp Version 2020.5.1 on Linux with the bundled installer.
I used the SAMLRaider version with the PR #41 that fixes an issue regarding failed signing. Maybe this solves the problem.

I'll close the issue. You can reopen it if you still can reproduce and provide some details.

Thanks & best regards,
Emanuel

**Comment by mindfuckup** [comment]
I just verified with the current stable version from the BApp store and I also cannot reproduce the issue there. JFYI.

**Comment by NAuclert** [comment]
Hi,

When I run the plugin on Windows with Burp Pro v2022.3.6 and embedded JRE 17.0.2, I am getting the same problem (resigning get stuck at "Signing ..."). Also, certificate doesn't get send to SAML Raider Certificates tab when using Send button.

I then tried on Linux with Burp Community v2021.10.3 and JRE 11.0.14 and it works great ... however the first config is more up-to-date and moreover, it is my main config so it would be nice to have a fix for it.

Great work otherwise, thank you !

**Comment by emanuelduss** [comment]
Hi

Thanks for the input. It sounds like some Burp internals changed and there might be a problem in current versions.

I'll try to figure out what happens the next time I work on the project. I can't give you an exact time tough.

THX!
Best,
Emanuel

**Comment by edmacke** [comment]
I also noticed the "Send Certificate to SAML Raider Certificates" does nothing. No error, but no certificate in the "SAML Raider Certificates" tab either.

**Comment by emanuelduss** [comment]
Fixed in release v1.4.1 (https://github.com/CompassSecurity/SAMLRaider/releases/tag/v1.4.1).
