### ISSUE TITLE
SAML Response not showing colored

### ISSUE THREAD

**Issue by HacKeD0x90** [CompassSecurity/SAMLRaider#45]
Hello, just trivial issue, 
SAML response not showing colored in my burp which make it hard to understand the assertion , in adddition the search is not working , SAML raider version 1.2.3 and i tried both burp 1.7.31 and 2020.4.
regarding java version tried 11 and 13 
![image](https://user-images.githubusercontent.com/14231783/87920755-b3db1b00-ca8a-11ea-9311-428a0f028efa.png)

**Comment by mindfuckup** [comment]
Hi

I had to remove the syntax coloring because of an issue. AFAIK the issue should be solved by now. I have to check if I have some time, but this is low-prio ;-)

Happy hacking,
Emanuel

**Comment by HacKeD0x90** [comment]
yes sure, no problem.
TYT.
Thanks.

**Comment by mindfuckup** [comment]
Will not be implemented. The used ITextEditor does not support syntax highlighting. https://portswigger.net/burp/extender/api/burp/itexteditor.html
