### ISSUE TITLE
Parsed & Prettified Sometimes Blank

### ISSUE THREAD

**Issue by edmacke** [CompassSecurity/SAMLRaider#54]
I haven't found a pattern yet, but the "Parsed & Prettified" XML section of the "SAML Message Info" tab will be blank. 

It doesn't appear to be anything wrong with the XML itself, and it *seems* random... I can click on the request and the Prettify will be blank. I click on some other request, and then come back to the first request and now the Prettify will be populated just fine. In other words, a given request will Prettify fine one time and not the next, or vice versa.

**Comment by mindfuckup** [comment]
Thanks for the input. I'll keep an eye on it when I use the extension in the future. If you find a pattern, this is still appreciated.

**Comment by t-hg** [comment]
I will close this issue. Feel free to create a new issue if this is still recurring.
