### ISSUE TITLE
Signing...

### ISSUE THREAD

**Issue by giuseppe-toscano** [CompassSecurity/SAMLRaider#60]
Hello,

I'm trying to use your extension on Burp, however I am encountering some problems.. In particular, if I try to click on the "(Re-)Sign Assertion" button to generate a new signature for a SAML response, it does not work and the message info continues to say "Signing..." (see the attached screenshot). I've already tried to uninstall and reinstall the extension, but nothing changes.. Can you help me? Thanks.

[image](https://user-images.githubusercontent.com/74903968/167486817-da7990f9-53eb-47d2-923a-9b35150bdf5d.png)

**Comment by emanuelduss** [comment]
Hi

Do you only have the problem with your imported certificate or also with cloned certificates? Can you try with a cloned one?

**Comment by giuseppe-toscano** [comment]
> Hi
> 
> 
> 
> Do you only have the problem with your imported certificate or also with cloned certificates? Can you try with a cloned one?

Hi, the problem persists also with cloned certificates..

**Comment by emanuelduss** [comment]
There could be a problem in the latest Burp version. This might be related (see latest comment): https://github.com/CompassSecurity/SAMLRaider/issues/42

- What OS do you use?
- Which Version do you use?
- Which JRE do you use (version? externally installed or JRE shipped with Burp Installation?)

**Comment by emanuelduss** [comment]
I can reproduce the issue with:
- Kali Linux
- Burp Suite Pro (installer version)
- Shipped JDK (openjdk 17.0.2 2022-01-18)

I don't have the issue with:
- Kali LInux
- Burp Community
- Java 13.0.5.1 2020-11-06

**Comment by edmacke** [comment]
That fix worked for me! Thanks for addressing it so quickly!

**Comment by emanuelduss** [comment]
THX for testing @edmacke.

Fixed in release v1.4.1 (https://github.com/CompassSecurity/SAMLRaider/releases/tag/v1.4.1).
