### ISSUE TITLE
Illegal base64 character

### ISSUE THREAD

**Issue by DG9Jww** [CompassSecurity/SAMLRaider#65]
![image](https://user-images.githubusercontent.com/84201009/193213908-e2d13ec1-7df6-40f3-9431-98be4ac7c9db.png)

![image](https://user-images.githubusercontent.com/84201009/193213994-30c0c189-9e81-4173-a059-07ba3de6ca5d.png)

I think the format of certificate is right.When I selected the certificate and clicked `Send Certificate to SAML Raider Certificates`, error appeared

**Comment by emanuelduss** [comment]
Hi

Thanks for your report. I'll have a look into it the next time I work on SAML Raider. Can you post the certificate as text here so I have an example to reproduce?

THX

**Comment by emanuelduss** [comment]
Thanks. I'll look into it the next time I work on the project.

**Comment by emanuelduss** [comment]
There is a temporary workaround.

Copy the certificate from the decoded SAML message in a file and add the PEM headers:
```
-----BEGIN CERTIFICATE-----

CERTIFICATE_FROM_PARSED_SAML_MESSAGE

-----END CERTIFICATE-----
```

Import it manually:

![image](https://user-images.githubusercontent.com/438188/206420779-4f68c493-0919-4f1f-8e4c-fc1c2370ee0e.png)


Then you have the cert in SAML Raider.

Best,
Mänu

**Comment by DG9Jww** [comment]
@emanuelduss  Thanks

**Comment by emanuelduss** [comment]
Looks like a general issue for all certificates, not specific to the certificate. I'll try to fix it the next time I work on the project.

**Comment by ville87** [comment]
just came across the same bug, I'm glad it's already on your backlog and thanks for the workaround :)

**Comment by t-hg** [comment]
Illegal base64 character a means that the string contains the character 0x0a, which is the newline character (\n). This is because the certificate is split into multiple lines as we know it from the PEM format. This should be fixed in the new major release.
