### ISSUE TITLE
XML Document parser messes up the document

### ISSUE THREAD

**Issue by northdpole** [CompassSecurity/SAMLRaider#7]
Hey, sorry for the bad title
Essentially, the strings provided by Burp's deocder (after url and Base64 decoding) and Raider are different in that the raider XML parser has attempted to "fix" the document and has added elements such as

```
   <?xml version="1.0" encoding="UTF-8"?>
```

also it has rearranged the document's elements or the attributes of the elements
That makes raider fail to produce an acceptable request if the server implements schema validation or just expects it's own version of the xml document.

Here's also a test that will fail on the latest master branch

```
@Test
public void testXmlLoadsCorrectly() throws IOException, SAXException, ParserConfigurationException, TransformerException {
    String msg = messageSimpleSAMLphpWithSig;
    Document document = xmlHelpers.getXMLDocumentOfSAMLMessage(msg);

    String docString = xmlHelpers.getString(document);
    assertTrue(docString.trim().replaceAll("\\s+", "").equalsIgnoreCase(msg));
}
```

The problem is with ipsilon and free ipa

**Comment by t-hg** [comment]
I will close this issue. Please feel free to create a new issue.
